/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HistoriaSlugRouteImport } from './routes/historia.$slug'
import { Route as DebugPixarTestRouteImport } from './routes/debug.pixar-test'
import { Route as DebugPixarPilotoRouteImport } from './routes/debug.pixar-piloto'
import { Route as DebugNoe20RouteImport } from './routes/debug.noe-20'
import { Route as DebugColoringProgressRouteImport } from './routes/debug.coloring-progress'
import { Route as ColorirSlugRouteImport } from './routes/colorir.$slug'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'
import { Route as ApiProfileRouteImport } from './routes/api.profile'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminQaCapasRouteImport } from './routes/admin.qa-capas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminIdiomasRouteImport } from './routes/admin.idiomas'
import { Route as AdminHistoriasRouteImport } from './routes/admin.historias'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as ApiPerfectpayWebhookRouteImport } from './routes/api.perfectpay.webhook'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiAdminReportsRouteImport } from './routes/api.admin.reports'
import { Route as ApiAdminMetricsRouteImport } from './routes/api.admin.metrics'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HistoriaSlugRoute = HistoriaSlugRouteImport.update({
  id: '/historia/$slug',
  path: '/historia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugPixarTestRoute = DebugPixarTestRouteImport.update({
  id: '/debug/pixar-test',
  path: '/debug/pixar-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugPixarPilotoRoute = DebugPixarPilotoRouteImport.update({
  id: '/debug/pixar-piloto',
  path: '/debug/pixar-piloto',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugNoe20Route = DebugNoe20RouteImport.update({
  id: '/debug/noe-20',
  path: '/debug/noe-20',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugColoringProgressRoute = DebugColoringProgressRouteImport.update({
  id: '/debug/coloring-progress',
  path: '/debug/coloring-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorirSlugRoute = ColorirSlugRouteImport.update({
  id: '/colorir/$slug',
  path: '/colorir/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/categorias/$slug',
  path: '/categorias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQaCapasRoute = AdminQaCapasRouteImport.update({
  id: '/qa-capas',
  path: '/qa-capas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdiomasRoute = AdminIdiomasRouteImport.update({
  id: '/idiomas',
  path: '/idiomas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoriasRoute = AdminHistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPerfectpayWebhookRoute = ApiPerfectpayWebhookRouteImport.update({
  id: '/api/perfectpay/webhook',
  path: '/api/perfectpay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportsRoute = ApiAdminReportsRouteImport.update({
  id: '/api/admin/reports',
  path: '/api/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMetricsRoute = ApiAdminMetricsRouteImport.update({
  id: '/api/admin/metrics',
  path: '/api/admin/metrics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/historias': typeof AdminHistoriasRoute
  '/admin/idiomas': typeof AdminIdiomasRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/qa-capas': typeof AdminQaCapasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/profile': typeof ApiProfileRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/colorir/$slug': typeof ColorirSlugRoute
  '/debug/coloring-progress': typeof DebugColoringProgressRoute
  '/debug/noe-20': typeof DebugNoe20Route
  '/debug/pixar-piloto': typeof DebugPixarPilotoRoute
  '/debug/pixar-test': typeof DebugPixarTestRoute
  '/historia/$slug': typeof HistoriaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/reports': typeof ApiAdminReportsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/perfectpay/webhook': typeof ApiPerfectpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/historias': typeof AdminHistoriasRoute
  '/admin/idiomas': typeof AdminIdiomasRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/qa-capas': typeof AdminQaCapasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/profile': typeof ApiProfileRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/colorir/$slug': typeof ColorirSlugRoute
  '/debug/coloring-progress': typeof DebugColoringProgressRoute
  '/debug/noe-20': typeof DebugNoe20Route
  '/debug/pixar-piloto': typeof DebugPixarPilotoRoute
  '/debug/pixar-test': typeof DebugPixarTestRoute
  '/historia/$slug': typeof HistoriaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/categorias': typeof CategoriasIndexRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/reports': typeof ApiAdminReportsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/perfectpay/webhook': typeof ApiPerfectpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/historias': typeof AdminHistoriasRoute
  '/admin/idiomas': typeof AdminIdiomasRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/qa-capas': typeof AdminQaCapasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/profile': typeof ApiProfileRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/colorir/$slug': typeof ColorirSlugRoute
  '/debug/coloring-progress': typeof DebugColoringProgressRoute
  '/debug/noe-20': typeof DebugNoe20Route
  '/debug/pixar-piloto': typeof DebugPixarPilotoRoute
  '/debug/pixar-test': typeof DebugPixarTestRoute
  '/historia/$slug': typeof HistoriaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/reports': typeof ApiAdminReportsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/perfectpay/webhook': typeof ApiPerfectpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buscar'
    | '/favoritos'
    | '/home'
    | '/perfil'
    | '/reset-password'
    | '/admin/banners'
    | '/admin/branding'
    | '/admin/categorias'
    | '/admin/emails'
    | '/admin/historias'
    | '/admin/idiomas'
    | '/admin/integracoes'
    | '/admin/login'
    | '/admin/qa-capas'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/api/profile'
    | '/categorias/$slug'
    | '/colorir/$slug'
    | '/debug/coloring-progress'
    | '/debug/noe-20'
    | '/debug/pixar-piloto'
    | '/debug/pixar-test'
    | '/historia/$slug'
    | '/admin/'
    | '/categorias/'
    | '/api/admin/metrics'
    | '/api/admin/reports'
    | '/api/admin/users'
    | '/api/perfectpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/favoritos'
    | '/home'
    | '/perfil'
    | '/reset-password'
    | '/admin/banners'
    | '/admin/branding'
    | '/admin/categorias'
    | '/admin/emails'
    | '/admin/historias'
    | '/admin/idiomas'
    | '/admin/integracoes'
    | '/admin/login'
    | '/admin/qa-capas'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/api/profile'
    | '/categorias/$slug'
    | '/colorir/$slug'
    | '/debug/coloring-progress'
    | '/debug/noe-20'
    | '/debug/pixar-piloto'
    | '/debug/pixar-test'
    | '/historia/$slug'
    | '/admin'
    | '/categorias'
    | '/api/admin/metrics'
    | '/api/admin/reports'
    | '/api/admin/users'
    | '/api/perfectpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buscar'
    | '/favoritos'
    | '/home'
    | '/perfil'
    | '/reset-password'
    | '/admin/banners'
    | '/admin/branding'
    | '/admin/categorias'
    | '/admin/emails'
    | '/admin/historias'
    | '/admin/idiomas'
    | '/admin/integracoes'
    | '/admin/login'
    | '/admin/qa-capas'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/api/profile'
    | '/categorias/$slug'
    | '/colorir/$slug'
    | '/debug/coloring-progress'
    | '/debug/noe-20'
    | '/debug/pixar-piloto'
    | '/debug/pixar-test'
    | '/historia/$slug'
    | '/admin/'
    | '/categorias/'
    | '/api/admin/metrics'
    | '/api/admin/reports'
    | '/api/admin/users'
    | '/api/perfectpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  FavoritosRoute: typeof FavoritosRoute
  HomeRoute: typeof HomeRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiProfileRoute: typeof ApiProfileRoute
  CategoriasSlugRoute: typeof CategoriasSlugRoute
  ColorirSlugRoute: typeof ColorirSlugRoute
  DebugColoringProgressRoute: typeof DebugColoringProgressRoute
  DebugNoe20Route: typeof DebugNoe20Route
  DebugPixarPilotoRoute: typeof DebugPixarPilotoRoute
  DebugPixarTestRoute: typeof DebugPixarTestRoute
  HistoriaSlugRoute: typeof HistoriaSlugRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  ApiAdminMetricsRoute: typeof ApiAdminMetricsRoute
  ApiAdminReportsRoute: typeof ApiAdminReportsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiPerfectpayWebhookRoute: typeof ApiPerfectpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/historia/$slug': {
      id: '/historia/$slug'
      path: '/historia/$slug'
      fullPath: '/historia/$slug'
      preLoaderRoute: typeof HistoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/pixar-test': {
      id: '/debug/pixar-test'
      path: '/debug/pixar-test'
      fullPath: '/debug/pixar-test'
      preLoaderRoute: typeof DebugPixarTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/pixar-piloto': {
      id: '/debug/pixar-piloto'
      path: '/debug/pixar-piloto'
      fullPath: '/debug/pixar-piloto'
      preLoaderRoute: typeof DebugPixarPilotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/noe-20': {
      id: '/debug/noe-20'
      path: '/debug/noe-20'
      fullPath: '/debug/noe-20'
      preLoaderRoute: typeof DebugNoe20RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/coloring-progress': {
      id: '/debug/coloring-progress'
      path: '/debug/coloring-progress'
      fullPath: '/debug/coloring-progress'
      preLoaderRoute: typeof DebugColoringProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colorir/$slug': {
      id: '/colorir/$slug'
      path: '/colorir/$slug'
      fullPath: '/colorir/$slug'
      preLoaderRoute: typeof ColorirSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/categorias/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qa-capas': {
      id: '/admin/qa-capas'
      path: '/qa-capas'
      fullPath: '/admin/qa-capas'
      preLoaderRoute: typeof AdminQaCapasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/idiomas': {
      id: '/admin/idiomas'
      path: '/idiomas'
      fullPath: '/admin/idiomas'
      preLoaderRoute: typeof AdminIdiomasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/historias': {
      id: '/admin/historias'
      path: '/historias'
      fullPath: '/admin/historias'
      preLoaderRoute: typeof AdminHistoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/perfectpay/webhook': {
      id: '/api/perfectpay/webhook'
      path: '/api/perfectpay/webhook'
      fullPath: '/api/perfectpay/webhook'
      preLoaderRoute: typeof ApiPerfectpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reports': {
      id: '/api/admin/reports'
      path: '/api/admin/reports'
      fullPath: '/api/admin/reports'
      preLoaderRoute: typeof ApiAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/metrics': {
      id: '/api/admin/metrics'
      path: '/api/admin/metrics'
      fullPath: '/api/admin/metrics'
      preLoaderRoute: typeof ApiAdminMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminHistoriasRoute: typeof AdminHistoriasRoute
  AdminIdiomasRoute: typeof AdminIdiomasRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminQaCapasRoute: typeof AdminQaCapasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminHistoriasRoute: AdminHistoriasRoute,
  AdminIdiomasRoute: AdminIdiomasRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminQaCapasRoute: AdminQaCapasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuscarRoute: BuscarRoute,
  FavoritosRoute: FavoritosRoute,
  HomeRoute: HomeRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiProfileRoute: ApiProfileRoute,
  CategoriasSlugRoute: CategoriasSlugRoute,
  ColorirSlugRoute: ColorirSlugRoute,
  DebugColoringProgressRoute: DebugColoringProgressRoute,
  DebugNoe20Route: DebugNoe20Route,
  DebugPixarPilotoRoute: DebugPixarPilotoRoute,
  DebugPixarTestRoute: DebugPixarTestRoute,
  HistoriaSlugRoute: HistoriaSlugRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  ApiAdminMetricsRoute: ApiAdminMetricsRoute,
  ApiAdminReportsRoute: ApiAdminReportsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiPerfectpayWebhookRoute: ApiPerfectpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
