// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czdhcazibequfovrqemj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6ZGhjYXppYmVxdWZvdnJxZW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NTM4NDksImV4cCI6MjA5MjUyOTg0OX0.V3bPyANE8Z9GKCCA75zeCyJfkHm15rn_Z5HfdTJeRQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});